{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: durarun-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: durarun
{{- end }}
