//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Hand-written deep copy functions for durarun.io/v1alpha1 API types.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// Ensure corev1 import is used (for RuntimeSpec deep copy).
var _ = corev1.EnvVar{}

// --- AgentJob ---

func (in *AgentJob) DeepCopyInto(out *AgentJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AgentJob) DeepCopy() *AgentJob {
	if in == nil {
		return nil
	}
	out := new(AgentJob)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- AgentJobSpec ---

func (in *AgentJobSpec) DeepCopyInto(out *AgentJobSpec) {
	*out = *in
	in.Runtime.DeepCopyInto(&out.Runtime)
	in.Execution.DeepCopyInto(&out.Execution)
	out.Checkpoint = in.Checkpoint
}

func (in *AgentJobSpec) DeepCopy() *AgentJobSpec {
	if in == nil {
		return nil
	}
	out := new(AgentJobSpec)
	in.DeepCopyInto(out)
	return out
}

// --- RuntimeSpec ---

func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

func (in *RuntimeSpec) DeepCopy() *RuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// --- ExecutionSpec ---

func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

func (in *ExecutionSpec) DeepCopy() *ExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// --- CheckpointPolicy ---

func (in *CheckpointPolicy) DeepCopyInto(out *CheckpointPolicy) {
	*out = *in
}

func (in *CheckpointPolicy) DeepCopy() *CheckpointPolicy {
	if in == nil {
		return nil
	}
	out := new(CheckpointPolicy)
	in.DeepCopyInto(out)
	return out
}

// --- AttemptReference ---

func (in *AttemptReference) DeepCopyInto(out *AttemptReference) {
	*out = *in
}

func (in *AttemptReference) DeepCopy() *AttemptReference {
	if in == nil {
		return nil
	}
	out := new(AttemptReference)
	in.DeepCopyInto(out)
	return out
}

// --- AgentJobStatus ---

func (in *AgentJobStatus) DeepCopyInto(out *AgentJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveAttempt != nil {
		in, out := &in.ActiveAttempt, &out.ActiveAttempt
		*out = new(AttemptReference)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

func (in *AgentJobStatus) DeepCopy() *AgentJobStatus {
	if in == nil {
		return nil
	}
	out := new(AgentJobStatus)
	in.DeepCopyInto(out)
	return out
}

// --- AgentJobList ---

func (in *AgentJobList) DeepCopyInto(out *AgentJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AgentJobList) DeepCopy() *AgentJobList {
	if in == nil {
		return nil
	}
	out := new(AgentJobList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- ObjectRef ---

func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// --- ArtifactRef ---

func (in *ArtifactRef) DeepCopyInto(out *ArtifactRef) {
	*out = *in
}

func (in *ArtifactRef) DeepCopy() *ArtifactRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactRef)
	in.DeepCopyInto(out)
	return out
}

// --- ResourceSpec (kept for SandboxPool) ---

func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// --- IsolationSpec (kept for SandboxPool) ---

func (in *IsolationSpec) DeepCopyInto(out *IsolationSpec) {
	*out = *in
}

func (in *IsolationSpec) DeepCopy() *IsolationSpec {
	if in == nil {
		return nil
	}
	out := new(IsolationSpec)
	in.DeepCopyInto(out)
	return out
}

// --- AgentAttempt ---

func (in *AgentAttempt) DeepCopyInto(out *AgentAttempt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AgentAttempt) DeepCopy() *AgentAttempt {
	if in == nil {
		return nil
	}
	out := new(AgentAttempt)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentAttempt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- AgentAttemptSpec ---

func (in *AgentAttemptSpec) DeepCopyInto(out *AgentAttemptSpec) {
	*out = *in
	out.JobRef = in.JobRef
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = (*in).DeepCopy()
	}
}

func (in *AgentAttemptSpec) DeepCopy() *AgentAttemptSpec {
	if in == nil {
		return nil
	}
	out := new(AgentAttemptSpec)
	in.DeepCopyInto(out)
	return out
}

// --- AgentAttemptStatus ---

func (in *AgentAttemptStatus) DeepCopyInto(out *AgentAttemptStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
	if in.Signal != nil {
		in, out := &in.Signal, &out.Signal
		*out = new(int32)
		**out = **in
	}
	if in.ArtifactRef != nil {
		in, out := &in.ArtifactRef, &out.ArtifactRef
		*out = new(ArtifactRef)
		**out = **in
	}
}

func (in *AgentAttemptStatus) DeepCopy() *AgentAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(AgentAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// --- AgentAttemptList ---

func (in *AgentAttemptList) DeepCopyInto(out *AgentAttemptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentAttempt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AgentAttemptList) DeepCopy() *AgentAttemptList {
	if in == nil {
		return nil
	}
	out := new(AgentAttemptList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentAttemptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- SandboxPool ---

func (in *SandboxPool) DeepCopyInto(out *SandboxPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SandboxPool) DeepCopy() *SandboxPool {
	if in == nil {
		return nil
	}
	out := new(SandboxPool)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- SandboxPoolSpec ---

func (in *SandboxPoolSpec) DeepCopyInto(out *SandboxPoolSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *SandboxPoolSpec) DeepCopy() *SandboxPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// --- PoolPodTemplate ---

func (in *PoolPodTemplate) DeepCopyInto(out *PoolPodTemplate) {
	*out = *in
	out.Resources = in.Resources
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *PoolPodTemplate) DeepCopy() *PoolPodTemplate {
	if in == nil {
		return nil
	}
	out := new(PoolPodTemplate)
	in.DeepCopyInto(out)
	return out
}

// --- SandboxPoolStatus ---

func (in *SandboxPoolStatus) DeepCopyInto(out *SandboxPoolStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
}

func (in *SandboxPoolStatus) DeepCopy() *SandboxPoolStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// --- SandboxPoolList ---

func (in *SandboxPoolList) DeepCopyInto(out *SandboxPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SandboxPoolList) DeepCopy() *SandboxPoolList {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
